[package]
name = "esexpr"
version = "0.1.20"
edition = "2021"
license = "Apache-2.0"
description = "ESExpr serialization format and related utilities."
documentation = "https://docs.rs/esexpr"
homepage = "https://github.com/argon-lang/esexpr"
repository = "https://github.com/argon-lang/esexpr"
categories = [ "encoding" ]
readme = "README.md"

[features]
default = []

[dependencies]
num-bigint = { workspace = true }
num-integer = { workspace = true }
esexpr-derive = { version = "0.1.20", path = "../esexpr_derive" }
derive_more = { version = "1.0.0", features = [ "full" ] }
