[package]
name = "esexpr"
version = "0.2.3"
edition = "2024"
rust-version = "1.90.0"
license = "Apache-2.0"
description = "ESExpr serialization format and related utilities."
documentation = "https://docs.rs/esexpr"
homepage = "https://github.com/argon-lang/esexpr"
repository = "https://github.com/argon-lang/esexpr"
categories = [ "encoding" ]
readme = "README.md"

[features]
default = ["std"]
std = ["esexpr-derive/macro_std", "num-bigint/std", "half/std"]

[dependencies]
num-bigint = { workspace = true }
esexpr-derive = { workspace = true }
half = { workspace = true }

[lints]
workspace = true
