[package]
name = "esexpr-derive"
version = "0.1.20"
edition = "2024"
rust-version = "1.88.0"
license = "Apache-2.0"
description = "ESExpr serialization format and related utilities."
documentation = "https://docs.rs/esexpr-derive"
homepage = "https://github.com/argon-lang/esexpr"
repository = "https://github.com/argon-lang/esexpr"
categories = [ "encoding" ]
readme = "README.md"

[lib]
proc-macro = true

[features]
default = ["macro_std"]
macro_std = []

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[lints]
workspace = true

