[package]
name = "esexpr-binary"
version = "0.1.20"
edition = "2021"
license = "Apache-2.0"
description = "ESExpr serialization binary format."
documentation = "https://docs.rs/esexpr-binary"
homepage = "https://github.com/argon-lang/esexpr"
repository = "https://github.com/argon-lang/esexpr"
categories = [ "encoding" ]
readme = "README.md"

[dependencies]
esexpr = { path = "../esexpr", version = "0.1.20" }
num-bigint = "0.4.6"
derive_more = { version = "1.0.0", features = [ "full" ] }
itertools = "0.14.0"
static_assertions = "1.1.0"

[dev-dependencies]
serde_json = { version = "1.0.138", features = ["float_roundtrip"] }
esexpr-json = { version = "0.1.20", path = "../esexpr_json" }
