[package]
name = "esexpr-text"
version = "0.2.1"
edition = "2024"
rust-version = "1.88.0"
license = "Apache-2.0"
description = "ESExpr serialization text format."
documentation = "https://docs.rs/esexpr-text"
homepage = "https://github.com/argon-lang/esexpr"
repository = "https://github.com/argon-lang/esexpr"
categories = [ "encoding" ]
readme = "README.md"

[dependencies]
esexpr = { workspace = true }
half = { workspace = true }
hexponent = { workspace = true }
num-bigint = { workspace = true }
nom = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
esexpr-json = { workspace = true }

[lints]
workspace = true
