[package]
name = "esexpr-derive"
version = "0.1.20"
edition = "2021"
license = "Apache-2.0"
description = "ESExpr serialization format and related utilities."
documentation = "https://docs.rs/esexpr-derive"
homepage = "https://github.com/argon-lang/esexpr"
repository = "https://github.com/argon-lang/esexpr"
categories = [ "encoding" ]
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
derive-syn-parse = "0.2.0"
proc-macro2 = "1.0.93"
quote = "1.0.38"
regex = "1.11.1"
syn = { version = "2.0.96", features = ["derive", "full"] }

[dev-dependencies]
syn = { version = "2.0.96", features = ["derive", "full", "visit"] }
