[workspace]
resolver = "2"

members = [
    "esexpr",
    "esexpr-binary",
    "esexpr-derive",
    "esexpr-examples",
    "esexpr-json",
    "esexpr-text",
    "esexpr-utils",
]

[workspace.dependencies]
base64 = { version = "0.22.1", default-features = false, features = ["alloc"] }
derive_more = { version = "2.0.1", default-features = false, features = [ "full" ] }
esexpr = { version = "0.1.20", path = "esexpr", default-features = false }
esexpr-binary = { version = "0.1.20", path = "esexpr-binary", default-features = false }
esexpr-derive = { version = "0.1.20", path = "esexpr-derive", default-features = false }
esexpr-json = { version = "0.1.20", path = "esexpr-json", default-features = false }
esexpr-text = { version = "0.1.20", path = "esexpr-text", default-features = false }
futures = { version = "0.3.31", default-features = false }
hexponent = {version = "0.3.1", default-features = false}
nom = { version = "8.0.0", default-features = false, features = ["alloc"] }
num-bigint = { version = "0.4.6", default-features = false }
proc-macro2 = "1.0.95"
quote = "1.0.40"
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.140", default-features = false, features = ["float_roundtrip", "alloc"] }
static_assertions = "1.1.0"
syn = { version = "2.0.103", features = ["derive", "full"] }

[workspace.lints.rust]
macro_use_extern_crate = "deny"
unused_must_use = "deny"
missing_docs = "deny"

[workspace.lints.clippy]
correctness = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }
complexity = { level = "deny", priority = -1 }
perf = { level = "deny", priority = -1 }
style = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
allow_attributes_without_reason = "deny"
as_pointer_underscore = "deny"
as_underscore = "deny"
unwrap_used = "deny"
needless_lifetimes = "allow"
elidable_lifetime_names = "allow"
match_wildcard_for_single_variants = "allow"
single_match_else = "allow"
too_many_lines = "allow"
needless_pass_by_value = "allow"
collapsible_else_if = "allow"
similar_names = "allow"
mismatching_type_param_order = "allow"
ignored_unit_patterns = "allow"
tabs_in_doc_comments = "allow"
wildcard_imports = "allow"

