[package]
name = "esexpr-json"
version = "0.2.0"
edition = "2024"
rust-version = "1.88.0"
license = "Apache-2.0"
description = "ESExpr serialization JSON encoding mappings."
documentation = "https://docs.rs/esexpr-text"
homepage = "https://github.com/argon-lang/esexpr"
repository = "https://github.com/argon-lang/esexpr"
categories = [ "encoding" ]
readme = "README.md"

[dependencies]
base64 = { workspace = true }
esexpr = { workspace = true }
half = { workspace = true }
num-bigint = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
