/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.argon.esexpr;

import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.module.SimpleModule;
import com.fasterxml.jackson.core.type.TypeReference;
import org.apache.commons.io.FilenameUtils;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.math.BigInteger;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

class BinaryEncodingTest {
	@ParameterizedTest
	@MethodSource("fileProvider")
	public void binaryEncoding(Path jsonPath) throws Exception {
		var esxbPath = jsonPath.resolveSibling(FilenameUtils.removeExtension(jsonPath.getFileName().toString()) + ".esxb");


		var jsonValue = parseJson(Files.readString(jsonPath));
		var esxbValue = parseEsxb(Files.readAllBytes(esxbPath));
		var reencodedValue = new ArrayList<ESExpr>();
		for(var expr : esxbValue) {
			reencodedValue.add(parseEsxb1(encodeEsxb(expr)));
		}

		assertEquals(jsonValue, esxbValue);
		assertEquals(esxbValue, reencodedValue);
	}

	private List<ESExpr> parseJson(String value) throws Exception {
		var mapper = new ObjectMapper();

		var module = new SimpleModule();
		module.addDeserializer(ESExpr.class, new ESExprJsonDeserializer());
		mapper.registerModule(module);

		List<ESExpr> res;
		try {
			res = mapper.readValue(value, new TypeReference<List<ESExpr>>() {});
		}
		catch(JsonMappingException _) {
			res = List.of(mapper.readValue(value, ESExpr.class));
		}

		return res.stream()
			.map(e -> {
				if(e == null) {
					return new ESExpr.Null(BigInteger.ZERO);
				}
				else {
					return e;
				}
			})
			.toList();
	}

	private List<ESExpr> parseEsxb(byte[] value) throws Exception {
		var reader = new ESExprBinaryReader(new ByteArrayInputStream(value));
		return reader.readAll().toList();
	}

	private ESExpr parseEsxb1(byte[] value) throws Exception {
		var exprs = parseEsxb(value);

		assertEquals(1, exprs.size());
		return exprs.getFirst();
	}

	private byte[] encodeEsxb(ESExpr expr) throws Exception {
		var os = new ByteArrayOutputStream();
		var writer = new ESExprBinaryWriter(os);
		writer.write(expr);
		return os.toByteArray();
	}

	public static Stream<Path> fileProvider() throws IOException {
		Path directory = Paths.get("../../tests");
		return Files.list(directory)
			.filter(Files::isRegularFile)
			.filter(p -> FilenameUtils.getExtension(p.getFileName().toString()).equals("json"));
	}
}
