[package]
name = "esexpr-binary"
version = "0.2.1"
edition = "2024"
rust-version = "1.88.0"
license = "Apache-2.0"
description = "ESExpr serialization binary format."
documentation = "https://docs.rs/esexpr-binary"
homepage = "https://github.com/argon-lang/esexpr"
repository = "https://github.com/argon-lang/esexpr"
categories = [ "encoding" ]
readme = "README.md"

[features]
std = ["futures/std", "esexpr/std", "bytemuck/extern_crate_std"]
default = ["std"]

[dependencies]
bytemuck = { workspace = true }
esexpr = { workspace = true }
num-bigint = { workspace = true }
derive_more = { workspace = true }
futures = { workspace = true }
half = { workspace = true }
static_assertions = { workspace = true }

[dev-dependencies]
esexpr-json = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }

[lints]
workspace = true
